#include "MapDataIO.h"
#include "BSPCompiler.h"

#include <cstdio>
#include <cstring>
#include <ctime>
#include <vector>

// ---- Binary reader helpers ----

struct BinReader {
    std::vector<uint8_t> data;
    size_t pos = 0;

    bool load(const std::string& path) {
        FILE* f = fopen(path.c_str(), "rb");
        if (!f) return false;
        fseek(f, 0, SEEK_END);
        long sz = ftell(f);
        fseek(f, 0, SEEK_SET);
        data.resize(sz);
        size_t rd = fread(data.data(), 1, sz, f);
        fclose(f);
        return rd == (size_t)sz;
    }

    bool hasBytes(size_t n) const { return pos + n <= data.size(); }

    uint8_t readU8() { return data[pos++]; }
    int8_t readI8() { return (int8_t)data[pos++]; }

    uint16_t readU16() {
        uint16_t v = data[pos] | (data[pos + 1] << 8);
        pos += 2;
        return v;
    }

    int16_t readI16() { return (int16_t)readU16(); }

    int32_t readI32() {
        int32_t v = data[pos] | (data[pos + 1] << 8) | (data[pos + 2] << 16) | (data[pos + 3] << 24);
        pos += 4;
        return v;
    }

    uint32_t readU32() { return (uint32_t)readI32(); }

    int16_t readCoord() { return (int16_t)((data[pos++] & 0xFF) * 8); }

    bool readMarker(uint32_t expected) {
        uint32_t m = readU32();
        return m == expected;
    }

    bool readMarkerAny() {
        uint32_t m = readU32();
        return m == 0xDEADBEEF || m == 0xCAFEBABE;
    }

    void skip(size_t n) { pos += n; }
};

// ---- Binary writer helpers ----

struct BinWriter {
    std::vector<uint8_t> data;

    void writeU8(uint8_t v) { data.push_back(v); }
    void writeI8(int8_t v) { data.push_back((uint8_t)v); }

    void writeU16(uint16_t v) {
        data.push_back(v & 0xFF);
        data.push_back((v >> 8) & 0xFF);
    }

    void writeI16(int16_t v) { writeU16((uint16_t)v); }

    void writeI32(int32_t v) {
        data.push_back(v & 0xFF);
        data.push_back((v >> 8) & 0xFF);
        data.push_back((v >> 16) & 0xFF);
        data.push_back((v >> 24) & 0xFF);
    }

    void writeU32(uint32_t v) { writeI32((int32_t)v); }

    void writeCoord(int16_t v) { data.push_back((uint8_t)(v / 8)); }

    void writeMarker(uint32_t m) { writeU32(m); }

    void writeBytes(const uint8_t* src, size_t n) {
        data.insert(data.end(), src, src + n);
    }

    bool save(const std::string& path) {
        FILE* f = fopen(path.c_str(), "wb");
        if (!f) return false;
        size_t written = fwrite(data.data(), 1, data.size(), f);
        fclose(f);
        return written == data.size();
    }
};

// ---- Load implementation ----

bool MapDataIO::loadFromBin(const std::string& path, MapData& out, std::string& errorMsg) {
    BinReader r;
    if (!r.load(path)) {
        errorMsg = "Failed to open file: " + path;
        return false;
    }

    // Header (42 bytes)
    uint8_t version = r.readU8();
    if (version != 3) {
        errorMsg = "Bad map version: " + std::to_string(version);
        return false;
    }

    /*int32_t compileDate =*/ r.readI32();
    out.spawnIndex = r.readU16();
    out.spawnDir = r.readU8();
    out.flagsBitmask = (uint8_t)r.readI8();
    out.totalSecrets = (uint8_t)r.readI8();
    out.totalLoot = r.readU8();

    uint16_t numNodes = r.readU16();
    uint16_t dataSizePolys = r.readU16();
    uint16_t numLines = r.readU16();
    uint16_t numNormals = r.readU16();
    uint16_t numNormalSprites = r.readU16();
    int16_t numZSprites = r.readI16();
    int16_t numTileEvents = r.readI16();
    int16_t mapByteCodeSize = r.readI16();
    int8_t totalMayaCameras = r.readI8();
    int16_t totalMayaCameraKeys = r.readI16();

    // Maya tween offsets (6 shorts)
    for (int i = 0; i < 6; i++) {
        out.mayaTweenOffsets[i] = r.readI16();
    }

    int numMapSprites = numNormalSprites + numZSprites;

    // ---- Media section ----
    r.readMarker(0xDEADBEEF);
    uint16_t mediaCount = r.readU16();
    out.mediaIndices.resize(mediaCount);
    for (int i = 0; i < mediaCount; i++) {
        out.mediaIndices[i] = r.readU16();
    }
    r.readMarker(0xDEADBEEF);

    // ---- Normals (skip, will be regenerated by BSP compiler) ----
    r.skip(numNormals * 3 * 2);
    r.readMarkerAny(); // CAFEBABE

    // ---- BSP nodes (read for texture extraction) ----
    std::vector<int16_t> nodeOffsets(numNodes);
    for (int i = 0; i < numNodes; i++) nodeOffsets[i] = r.readI16();
    r.readMarkerAny();

    // nodeNormalIdxs (skip)
    r.skip(numNodes);
    r.readMarkerAny();

    // nodeChildOffset1 + nodeChildOffset2
    std::vector<int16_t> nodeChild1(numNodes), nodeChild2(numNodes);
    for (int i = 0; i < numNodes; i++) nodeChild1[i] = r.readI16();
    for (int i = 0; i < numNodes; i++) nodeChild2[i] = r.readI16();
    r.readMarkerAny();

    // nodeBounds
    std::vector<uint8_t> nodeBounds(numNodes * 4);
    for (int i = 0; i < numNodes * 4; i++) nodeBounds[i] = r.readU8();
    r.readMarkerAny();

    // ---- Polygon data (parse to extract per-tile textures) ----
    size_t polyStart = r.pos;
    std::vector<uint8_t> polyData(dataSizePolys);
    for (int i = 0; i < dataSizePolys; i++) polyData[i] = r.readU8();
    r.readMarkerAny();

    // Walk BSP leaf nodes to extract texture assignments per tile
    // Each leaf has bounds and polygon meshes with tileNum (texture ID)
    for (int n = 0; n < numNodes; n++) {
        if ((nodeOffsets[n] & 0xFFFF) != 0xFFFF) continue; // not a leaf

        // Leaf bounds in vertex-byte coords (world >> 7)
        uint8_t bMinX = nodeBounds[n * 4 + 0];
        uint8_t bMinY = nodeBounds[n * 4 + 1];
        uint8_t bMaxX = nodeBounds[n * 4 + 2];
        uint8_t bMaxY = nodeBounds[n * 4 + 3];

        // Parse polygon meshes at this leaf's poly data offset
        int offset = nodeChild1[n] & 0xFFFF;
        if (offset >= dataSizePolys) continue;

        int meshCount = polyData[offset++];
        int floorTileNum = -1;
        int wallTileNum = -1;

        for (int m = 0; m < meshCount && offset + 5 < dataSizePolys; m++) {
            offset += 4; // skip 4 reserved bytes
            uint16_t packed = polyData[offset] | (polyData[offset + 1] << 8);
            offset += 2;
            int tileNum = packed >> 7;
            int polyCount = packed & 0x7F;

            // Parse each polygon to determine if it's a floor (horizontal) or wall (vertical)
            for (int j = 0; j < polyCount && offset < dataSizePolys; j++) {
                int polyFlags = polyData[offset++];
                int numVerts = (polyFlags & 0x7) + 2;

                // Check first two vertices to classify as floor vs wall
                bool isFloor = false;
                if (numVerts >= 2 && offset + numVerts * 5 <= dataSizePolys) {
                    // Floor polygons have all Z values the same
                    uint8_t z0 = polyData[offset + 2];
                    bool allSameZ = true;
                    for (int k = 1; k < numVerts && allSameZ; k++) {
                        if (polyData[offset + k * 5 + 2] != z0) allSameZ = false;
                    }
                    isFloor = allSameZ;
                }

                if (isFloor && floorTileNum < 0) floorTileNum = tileNum;
                if (!isFloor && wallTileNum < 0) wallTileNum = tileNum;

                offset += numVerts * 5;
            }
        }

        // Map leaf bounds to tile grid and assign textures
        // Bounds are in vertex-byte coords (world >> 7). Tile = world / 64.
        // So tile = (byteCoord << 7) / 64 = byteCoord * 2.
        int tMinCol = (int)bMinX * 2;
        int tMinRow = (int)bMinY * 2;
        int tMaxCol = (int)bMaxX * 2;
        int tMaxRow = (int)bMaxY * 2;
        if (tMaxCol <= tMinCol) tMaxCol = tMinCol + 1;
        if (tMaxRow <= tMinRow) tMaxRow = tMinRow + 1;

        for (int row = tMinRow; row < tMaxRow && row < 32; row++) {
            for (int col = tMinCol; col < tMaxCol && col < 32; col++) {
                if (col < 0 || row < 0) continue;
                int idx = row * 32 + col;
                if (floorTileNum > 0 && out.tiles[idx].floorTexture <= 1) {
                    out.tiles[idx].floorTexture = floorTileNum;
                }
                if (wallTileNum > 0 && out.tiles[idx].wallTexture <= 1) {
                    out.tiles[idx].wallTexture = wallTileNum;
                }
            }
        }
    }

    // ---- Lines (skip, will be regenerated) ----
    r.skip((numLines + 1) / 2);       // lineFlags
    r.skip(numLines * 2);              // lineXs
    r.skip(numLines * 2);              // lineYs
    r.readMarkerAny();

    // ---- Height map ----
    for (int i = 0; i < 1024; i++) {
        out.tiles[i].height = r.readU8();
    }
    r.readMarkerAny();

    // ---- Sprite coordinates ----
    out.normalSprites.resize(numNormalSprites);
    out.zSprites.resize(numZSprites);

    // X coords
    for (int i = 0; i < numNormalSprites; i++) {
        out.normalSprites[i].x = r.readCoord();
    }
    for (int i = 0; i < numZSprites; i++) {
        out.zSprites[i].x = r.readCoord();
        out.zSprites[i].isZSprite = true;
    }

    // Y coords
    for (int i = 0; i < numNormalSprites; i++) {
        out.normalSprites[i].y = r.readCoord();
    }
    for (int i = 0; i < numZSprites; i++) {
        out.zSprites[i].y = r.readCoord();
    }

    // ---- Sprite info (lower 8 bits) ----
    for (int i = 0; i < numNormalSprites; i++) {
        out.normalSprites[i].info = r.readU8();
    }
    for (int i = 0; i < numZSprites; i++) {
        out.zSprites[i].info = r.readU8();
    }
    r.readMarkerAny();

    // ---- Sprite info (upper 16 bits) ----
    for (int i = 0; i < numNormalSprites; i++) {
        out.normalSprites[i].info |= ((uint32_t)r.readU16()) << 16;
    }
    for (int i = 0; i < numZSprites; i++) {
        out.zSprites[i].info |= ((uint32_t)r.readU16()) << 16;
    }
    r.readMarkerAny();

    // ---- Z-sprite heights ----
    for (int i = 0; i < numZSprites; i++) {
        out.zSprites[i].z = r.readU8();
    }
    r.readMarkerAny();

    // ---- Z-sprite info middle bits (bits 8-15) ----
    for (int i = 0; i < numZSprites; i++) {
        out.zSprites[i].info |= ((uint32_t)r.readU8()) << 8;
    }
    r.readMarkerAny();

    // ---- Static functions ----
    for (int i = 0; i < 12; i++) {
        out.staticFuncs[i] = r.readU16();
    }
    r.readMarkerAny();

    // ---- Tile events ----
    out.tileEvents.resize(numTileEvents);
    for (int i = 0; i < numTileEvents; i++) {
        out.tileEvents[i].packed = r.readI32();
        out.tileEvents[i].param = r.readI32();
    }
    r.readMarkerAny();

    // ---- Bytecode ----
    out.byteCode.resize(mapByteCodeSize);
    for (int i = 0; i < mapByteCodeSize; i++) {
        out.byteCode[i] = r.readU8();
    }
    r.readMarkerAny();

    // ---- Maya cameras ----
    out.mayaCameras.resize(totalMayaCameras);
    for (int i = 0; i < totalMayaCameras; i++) {
        auto& cam = out.mayaCameras[i];
        cam.numKeys = r.readU8();
        cam.sampleRate = r.readI16();

        // Key data: numKeys * 7 shorts
        cam.keyData.resize(cam.numKeys * 7);
        for (int j = 0; j < cam.numKeys * 7; j++) {
            cam.keyData[j] = r.readI16();
        }

        // Tween indices: numKeys * 6 shorts
        cam.tweenIndices.resize(cam.numKeys * 6);
        for (int j = 0; j < cam.numKeys * 6; j++) {
            cam.tweenIndices[j] = r.readI16();
        }

        // Tween counts: 6 shorts
        int totalTweens = 0;
        for (int j = 0; j < 6; j++) {
            cam.tweenCounts[j] = r.readI16();
            totalTweens += cam.tweenCounts[j];
        }

        r.readMarker(0xDEADBEEF);

        // Tween data
        cam.tweenData.resize(totalTweens);
        for (int j = 0; j < totalTweens; j++) {
            cam.tweenData[j] = r.readI8();
        }
    }
    r.readMarkerAny();

    // ---- Map flags (512 bytes nibble-packed -> 1024 tiles) ----
    // First clear tile event flags that were set during event loading
    for (int i = 0; i < 1024; i++) {
        out.tiles[i].flags = 0;
    }

    for (int i = 0; i < 512; i++) {
        uint8_t b = r.readU8();
        out.tiles[i * 2].flags = b & 0xF;
        out.tiles[i * 2 + 1].flags = (b >> 4) & 0xF;
    }
    r.readMarkerAny();

    // Re-apply tile event flag (bit 6 = 0x40) from tile events
    for (auto& ev : out.tileEvents) {
        int idx = ev.packed & 0x3FF;
        if (idx < 1024) {
            out.tiles[idx].flags |= 0x40;
        }
    }

    return true;
}

// ---- Save implementation ----

bool MapDataIO::saveToBin(const MapData& map, const std::string& path, std::string& errorMsg) {
    // Compile BSP from tile data
    BSPCompileResult bsp;
    if (!BSPCompiler::compile(map, bsp, errorMsg)) {
        return false;
    }

    int numNormalSprites = (int)map.normalSprites.size();
    int numZSprites = (int)map.zSprites.size();
    int numMapSprites = numNormalSprites + numZSprites;
    int numTileEvents = (int)map.tileEvents.size();
    int mapByteCodeSize = (int)map.byteCode.size();
    int totalMayaCameras = (int)map.mayaCameras.size();

    // Count total maya camera keys
    int16_t totalMayaCameraKeys = 0;
    for (auto& cam : map.mayaCameras) {
        totalMayaCameraKeys += cam.numKeys;
    }

    BinWriter w;

    // ---- Header (42 bytes) ----
    w.writeU8(3); // version
    w.writeI32((int32_t)time(nullptr)); // compile date
    w.writeU16(map.spawnIndex);
    w.writeU8(map.spawnDir);
    w.writeI8((int8_t)map.flagsBitmask);
    w.writeI8((int8_t)map.totalSecrets);
    w.writeU8(map.totalLoot);
    w.writeU16((uint16_t)bsp.nodes.size());
    w.writeU16((uint16_t)bsp.polyData.size());
    w.writeU16((uint16_t)bsp.lines.size());
    w.writeU16((uint16_t)(bsp.normals.size() / 3));
    w.writeU16((uint16_t)numNormalSprites);
    w.writeI16((int16_t)numZSprites);
    w.writeI16((int16_t)numTileEvents);
    w.writeI16((int16_t)mapByteCodeSize);
    w.writeI8((int8_t)totalMayaCameras);
    w.writeI16(totalMayaCameraKeys);

    // Maya tween offsets
    for (int i = 0; i < 6; i++) {
        w.writeI16(map.mayaTweenOffsets[i]);
    }

    // ---- Media section ----
    w.writeMarker(0xDEADBEEF);
    w.writeU16((uint16_t)map.mediaIndices.size());
    for (auto idx : map.mediaIndices) {
        w.writeU16(idx);
    }
    w.writeMarker(0xDEADBEEF);

    // ---- Normals ----
    for (auto n : bsp.normals) {
        w.writeI16(n);
    }
    w.writeMarker(0xCAFEBABE);

    // ---- Node offsets ----
    for (auto& node : bsp.nodes) {
        w.writeI16(node.offset);
    }
    w.writeMarker(0xCAFEBABE);

    // ---- Node normal indices ----
    for (auto& node : bsp.nodes) {
        w.writeU8(node.normalIdx);
    }
    w.writeMarker(0xCAFEBABE);

    // ---- Node child offsets ----
    for (auto& node : bsp.nodes) {
        w.writeI16(node.child1);
    }
    for (auto& node : bsp.nodes) {
        w.writeI16(node.child2);
    }
    w.writeMarker(0xCAFEBABE);

    // ---- Node bounds ----
    for (auto& node : bsp.nodes) {
        w.writeU8(node.bounds[0]);
        w.writeU8(node.bounds[1]);
        w.writeU8(node.bounds[2]);
        w.writeU8(node.bounds[3]);
    }
    w.writeMarker(0xCAFEBABE);

    // ---- Polygon data ----
    w.writeBytes(bsp.polyData.data(), bsp.polyData.size());
    w.writeMarker(0xCAFEBABE);

    // ---- Lines ----
    // lineFlags (nibble-packed)
    int numLines = (int)bsp.lines.size();
    for (int i = 0; i < (numLines + 1) / 2; i++) {
        uint8_t byte = 0;
        byte |= bsp.lines[i * 2].flags & 0xF;
        if (i * 2 + 1 < numLines) {
            byte |= (bsp.lines[i * 2 + 1].flags & 0xF) << 4;
        }
        w.writeU8(byte);
    }
    // lineXs
    for (auto& line : bsp.lines) {
        w.writeU8(line.x1);
        w.writeU8(line.x2);
    }
    // lineYs
    for (auto& line : bsp.lines) {
        w.writeU8(line.y1);
        w.writeU8(line.y2);
    }
    w.writeMarker(0xCAFEBABE);

    // ---- Height map ----
    for (int i = 0; i < 1024; i++) {
        w.writeU8(map.tiles[i].height);
    }
    w.writeMarker(0xCAFEBABE);

    // ---- Sprite coordinates (compressed) ----
    // X coords: normal sprites then z sprites
    for (auto& s : map.normalSprites) { w.writeCoord(s.x); }
    for (auto& s : map.zSprites) { w.writeCoord(s.x); }
    // Y coords
    for (auto& s : map.normalSprites) { w.writeCoord(s.y); }
    for (auto& s : map.zSprites) { w.writeCoord(s.y); }

    // ---- Sprite info lower 8 bits ----
    for (auto& s : map.normalSprites) { w.writeU8(s.info & 0xFF); }
    for (auto& s : map.zSprites) { w.writeU8(s.info & 0xFF); }
    w.writeMarker(0xCAFEBABE);

    // ---- Sprite info upper 16 bits ----
    for (auto& s : map.normalSprites) { w.writeU16((s.info >> 16) & 0xFFFF); }
    for (auto& s : map.zSprites) { w.writeU16((s.info >> 16) & 0xFFFF); }
    w.writeMarker(0xCAFEBABE);

    // ---- Z-sprite heights ----
    for (auto& s : map.zSprites) { w.writeU8(s.z); }
    w.writeMarker(0xCAFEBABE);

    // ---- Z-sprite info middle bits ----
    for (auto& s : map.zSprites) { w.writeU8((s.info >> 8) & 0xFF); }
    w.writeMarker(0xCAFEBABE);

    // ---- Static functions ----
    for (int i = 0; i < 12; i++) {
        w.writeU16(map.staticFuncs[i]);
    }
    w.writeMarker(0xCAFEBABE);

    // ---- Tile events ----
    for (auto& ev : map.tileEvents) {
        w.writeI32(ev.packed);
        w.writeI32(ev.param);
    }
    w.writeMarker(0xCAFEBABE);

    // ---- Bytecode ----
    w.writeBytes(map.byteCode.data(), map.byteCode.size());
    w.writeMarker(0xCAFEBABE);

    // ---- Maya cameras ----
    for (auto& cam : map.mayaCameras) {
        w.writeU8(cam.numKeys);
        w.writeI16(cam.sampleRate);

        for (auto v : cam.keyData) { w.writeI16(v); }
        for (auto v : cam.tweenIndices) { w.writeI16(v); }
        for (int j = 0; j < 6; j++) { w.writeI16(cam.tweenCounts[j]); }

        w.writeMarker(0xDEADBEEF);

        for (auto v : cam.tweenData) { w.writeI8(v); }
    }
    w.writeMarker(0xCAFEBABE);

    // ---- Map flags (nibble-packed) ----
    for (int i = 0; i < 512; i++) {
        uint8_t lo = map.tiles[i * 2].flags & 0xF;
        uint8_t hi = map.tiles[i * 2 + 1].flags & 0xF;
        w.writeU8(lo | (hi << 4));
    }
    w.writeMarker(0xCAFEBABE);

    // Write to file
    if (!w.save(path)) {
        errorMsg = "Failed to write file: " + path;
        return false;
    }

    return true;
}
