# embed_resources.cmake — Generate resources_embedded.h from YAML files
#
# Usage (from CMakeLists.txt):
#   cmake -DRESOURCES_DIR=... -DOUTPUT_FILE=... -P embed_resources.cmake

file(GLOB_RECURSE RESOURCE_FILES "${RESOURCES_DIR}/*.yaml")
list(SORT RESOURCE_FILES)

set(HEADER "#pragma once\n")
string(APPEND HEADER "// Auto-generated by embed_resources.cmake — do not edit.\n")
string(APPEND HEADER "#include <cstddef>\n\n")
string(APPEND HEADER "struct EmbeddedResource {\n")
string(APPEND HEADER "    const char* path;\n")
string(APPEND HEADER "    const char* content;\n")
string(APPEND HEADER "    size_t      length;\n")
string(APPEND HEADER "};\n\n")
string(APPEND HEADER "static const EmbeddedResource EMBEDDED_RESOURCES[] = {\n")

set(COUNT 0)
foreach(FILE_PATH ${RESOURCE_FILES})
    # Compute relative path from RESOURCES_DIR (e.g. "levels/01_tycho/level.yaml")
    file(RELATIVE_PATH REL_PATH "${RESOURCES_DIR}" "${FILE_PATH}")
    file(READ "${FILE_PATH}" FILE_CONTENT)

    # Escape backslashes and double-quotes for C++ string literal
    string(REPLACE "\\" "\\\\" FILE_CONTENT "${FILE_CONTENT}")
    string(REPLACE "\"" "\\\"" FILE_CONTENT "${FILE_CONTENT}")
    # Replace newlines with \n" "  (split across multiple string literals for readability)
    string(REPLACE "\n" "\\n\"\n    \"" FILE_CONTENT "${FILE_CONTENT}")

    # Get actual file size for the length field
    file(SIZE "${FILE_PATH}" FILE_SIZE)

    string(APPEND HEADER "    {\"${REL_PATH}\",\n")
    string(APPEND HEADER "    \"${FILE_CONTENT}\",\n")
    string(APPEND HEADER "    ${FILE_SIZE}},\n")

    math(EXPR COUNT "${COUNT} + 1")
endforeach()

string(APPEND HEADER "};\n\n")
string(APPEND HEADER "static const size_t EMBEDDED_RESOURCES_COUNT = ${COUNT};\n")

file(WRITE "${OUTPUT_FILE}" "${HEADER}")
message(STATUS "Embedded ${COUNT} resource files into ${OUTPUT_FILE}")
