#pragma once
#include "EntityMonster.h"
#include "AIComponent.h"
#include "LootComponent.h"
#include "GameSprite.h"
#include "LerpSprite.h"
#include "ScriptThread.h"

class EntityMonster;
class MayaCamera;
class Entity;
class GameSprite;
class LerpSprite;
class ScriptThread;
class OutputStream;
class InputStream;
class EntityDef;

class Applet;
class SDLGL;
struct GameConfig;

class Game
{
private:

public:
    Applet* app = nullptr;  // Set in startup(), replaces CAppContainer::getInstance()->app
    const GameConfig* gameConfig = nullptr; // Set in startup(), replaces CAppContainer::getInstance()->gameConfig
    SDLGL* sdlGL = nullptr;

    static constexpr int32_t dropDirs[] { 64, 0, 64, 64, 0, 64, -64, 64, -64, 0, -64, -64, 0, -64, 64, -64 };
    static constexpr int MAX_GRID_ENTITIES = 9;
    static constexpr int DEFAULT_MAX_ENTITIES = 275;
    int maxEntities = 0;
    static constexpr int FILE_NAME_FULLWORLD = 0;
    static constexpr int FILE_NAME_CONFIG = 1;
    static constexpr int FILE_NAME_BRIEFPLAYER = 2;
    static constexpr int FILE_NAME_FULLPLAYER = 3;
    static constexpr int FILE_NAME_BRIEFWORLD = 4;

    uint8_t* monsterSounds = nullptr;
	int OFS_MAYAKEY_X = 0;
	int OFS_MAYAKEY_Y = 0;
	int OFS_MAYAKEY_Z = 0;
	int OFS_MAYAKEY_PITCH = 0;
	int OFS_MAYAKEY_YAW = 0;
	int OFS_MAYAKEY_ROLL = 0;
	int OFS_MAYAKEY_MS = 0;
    short* ofsMayaTween = nullptr;
    int camPlayerX = 0;
    int camPlayerY = 0;
    int camPlayerZ = 0;
    int camPlayerYaw = 0;
    int camPlayerPitch = 0;
    MayaCamera* mayaCameras = nullptr;
    int totalMayaCameras = 0;
    int16_t* mayaCameraKeys = nullptr;
    int8_t* mayaCameraTweens = nullptr;
    int16_t* mayaTweenIndices = nullptr;
    int totalMayaCameraKeys = 0;
    int totalMayaTweens = 0;
    Entity* entities = nullptr;
    int numEntities = 0;
    Entity* entityDb[1024] = {};
    EntityMonster entityMonsters[80] = {};
    int numMonsters = 0;
    AIComponent aiComponents[80] = {};
    int numAIComponents = 0;
    LootComponent lootComponents[128] = {};
    int numLootComponents = 0;
    int spawnParam = 0;
    bool disableAI = false;
    bool skipMinigames = false;
    Entity* inactiveMonsters = nullptr;
    Entity* activeMonsters = nullptr;
    Entity* combatMonsters = nullptr;
    int cinUnpauseTime = 0;
    int lastTurnTime = 0;
    bool pauseGameTime = false;
    int firstDropIndex = 0;
    int dropIndex = 0;
    int lastDropEntIndex = 0;
    bool skippingCinematic = false;
    bool skipDialog = false;
    bool skipAdvanceTurn = false;
    bool queueAdvanceTurn = false;
    char keycode[7] = {};
    int monstersTurn = 0;
    bool monstersUpdated = false;
    bool interpolatingMonsters = false;
    bool gotoTriggered = false;
    bool isSaved = false;
    bool isLoaded = false;
    int eventFlags[2] = {};
    GameSprite gsprites[48] = {};
    int activeSprites = 0;
    int activePropogators = 0;
    int animatingEffects = 0;
    int changeMapParam = 0;
    int saveStateMap = 0;
    uint8_t difficulty = 0;
    int activeLoadType = 0;
    bool updateAutomap = false;
    bool hasSeenIntro = false;
    bool skipMovie = false;
    int levelVars[8] = {};
    int16_t* levelNames = nullptr;
    int levelNamesCount = 0; // Port: New
    int totalLevelTime = 0;
    int curLevelTime = 0;
    uint16_t lootFound = 0;
    uint16_t totalLoot = 0;
    MayaCamera* activeCamera = nullptr;
    int activeCameraTime = 0;
    int activeCameraKey = 0;
    bool activeCameraView = false;
    Entity* watchLine = nullptr;
    LerpSprite lerpSprites[16] = {};
    int numLerpSprites = 0;
    ScriptThread scriptThreads[20] = {};
    int numScriptThreads = 0;
    bool pathVisitedl[64] = {};
    short pathParents[64] = {};
    short pathSearches[64] = {};
    int numPathSearches = 0;
    bool secretActive = false;
    Entity* openDoors[6] = {};
    int viewX = 0;
    int viewY = 0;
    int viewAngle = 0;
    int destX = 0;
    int destY = 0;
    int destAngle = 0;
    int viewSin = 0;
    int viewCos = 0;
    int viewStepX = 0;
    int viewStepY = 0;
    int viewRightStepX = 0;
    int viewRightStepY = 0;
    short scriptStateVars[128] = {};
    uint8_t mapSecretsFound = 0;
    uint8_t totalSecrets = 0;
    int cinematicWeapon = 0;
    short entityDeathFunctions[128] = {};
    int numDestroyableObj = 0;
    int destroyedObj = 0;
    int placedBombs[4] = {};
    Entity* gridEntities[Game::MAX_GRID_ENTITIES] = {};
    int64_t curPath = 0;
    long unused_0x486c = 0; // never used
    int pathDepth = 0;
    int pathSearchDepth = 0;
    int64_t closestPath = 0;
    int closestPathDepth = 0;
    int closestPathDist = 0;
    int lineOfSight = 0;
    int lineOfSightWeight = 0;
    Entity* findEnt = nullptr;
    Entity* skipEnt = nullptr;
    int interactClipMask = 0;
    uint8_t visitOrder[8] = {};
    int visitDist[8] = {};
    int visitedTiles[32] = {};
    int baseVisitedTiles[32] = {};
    int numMallocsForVIOS = 0;
    bool angryVIOS = false;
    short numLevelLoads[10] = {};
    int totalPlayTime = 0;
    int lastSaveTime = 0;
    Entity* traceEntities[32] = {};
    int traceFracs[32] = {};
    int numTraceEntities = 0;
    int traceBoundingBox[4] = {};
    int tracePoints[4] = {};
    int traceCollisionX = 0;
    int traceCollisionY = 0;
    int traceCollisionZ = 0;
    Entity* traceEntity = nullptr;
    int posShift = 0;
    int angleShift = 0;
    int numCallThreads = 0;
    ScriptThread* callThreads[16] = {};

	// Constructor
	Game();
	// Destructor
	~Game();

	bool startup();
    void unlinkEntity(Entity* entity);
    void linkEntity(Entity* entity, int i, int i2);
    void unlinkWorldEntity(int i, int i2);
    void linkWorldEntity(int i, int i2);
    void removeEntity(Entity* entity);
    void trace(int n, int n2, int n3, int n4, Entity* entity, int n5, int n6);
    void trace(int n, int n2, int n3, int traceCollisionX, int traceCollisionY, int traceCollisionZ, Entity* entity, int n4, int n5, bool b);
    void loadMapEntities();
    void loadTableCamera(int i, int i2);
    void setKeyOffsets();
    void loadMayaCameras(InputStream* IS);
    void unloadMapData();
    bool touchTile(int n, int n2, bool b);
    void prepareMonsters();
    Entity* findMapEntity(int n, int n2);
    Entity* findMapEntity(int n, int n2, int n3);
    void activate(Entity* entity);
    void activate(Entity* entity, bool b, bool b2, bool b3, bool b4);
    void killAll();
    void deactivate(Entity* entity);
    void UpdatePlayerVars();
    void monsterAI();
    void monsterLerp();
    void spawnPlayer();
    void eventFlagsForMovement(int n, int n2, int n3, int n4);
    int eventFlagForDirection(int n, int n2);
    void givemap(int n, int n2, int n3, int n4);
    bool performDoorEvent(int n, Entity* entity, int n2);
    bool performDoorEvent(int n, Entity* entity, int n2, bool b);
    bool performDoorEvent(int n, ScriptThread* scriptThread, Entity* watchLine, int n2, bool b);
    void lerpSpriteAsDoor(int n, int n2, ScriptThread* scriptThread);
    void updatePlayerDoors(Entity* entity, bool b);
    bool CanCloseDoor(Entity* entity);
    void advanceTurn();
    void gsprite_clear(int n);
    GameSprite* gsprite_alloc(int n, int n2, int n3);
    GameSprite* gsprite_allocAnim(int n, int n2, int n3, int n4);
    void gsprite_destroy(GameSprite* gameSprite);
    void snapGameSprites();
    void gsprite_update(int n);
    void saveWorldState(OutputStream* OS, bool b);
    void loadWorldState();
    bool loadWorldState(InputStream* IS);
    void saveConfig();
    void loadConfig();
    void saveState(int lastMapID, int loadMapID, int viewX, int viewY, int viewAngle, int viewPitch, int prevX, int prevY, int saveX, int saveY, int saveZ, int saveAngle, int savePitch, int saveType);
    void saveLevelSnapshot();
    bool savePlayerState(OutputStream* OS,int loadMapID, int viewX, int viewY, int viewAngle, int viewPitch, int prevX, int prevY, int saveX, int saveY, int saveZ, int saveAngle, int savePitch);
    bool loadPlayerState(InputStream* IS);
    bool loadState(int activeLoadType);
    bool hasConfig();
    bool hasElement(const char* name);
    bool hasSavedState();
    void removeState(bool b);
    void saveEmptyConfig();
    bool canSnapMonsters();
    bool snapMonsters(bool b);
    void endMonstersTurn();
    void updateMonsters();
    void setLineLocked(Entity* entity, bool b);
    void snapAllMovers();
    void skipCinematic();
    int getNextBombIndex();
    void updateBombs();
    int setDynamite(int x, int y, bool b);
    Entity* getFreeDropEnt();
    void allocDynamite(int n, int n2, int n3, int n4, int n5, int n6);
    Entity* spawnDropItem(int n, int n2, int n3, EntityDef* def, int param, bool b);
    Entity* spawnDropItem(int n, int n2, int n3, int n4, int n5, int n6, int n7, bool b);
    void spawnDropItem(Entity* entity);
    Entity* spawnPlayerEntityCopy(int n, int n2);
    Entity* spawnSentryBotCorpse(int n, int n2, int n3, int n4, int n5);
    void throwDropItem(int dstX, int dstY, int n, Entity* entity);
    int updateLerpSprite(LerpSprite* lerpSprite);
    void snapLerpSprites(int n);
    void updateLerpSprites();
    LerpSprite* allocLerpSprite(ScriptThread* thread, int n, bool b);
    void freeLerpSprite(LerpSprite* lerpSprite);
    void runScriptThreads(int n);
    ScriptThread* allocScriptThread();
    void freeScriptThread(ScriptThread* scriptThread);
    bool isCameraActive();
    int executeTile(int n, int n2, int n3);
    bool doesScriptExist(int n, int n2, int n3);
    int executeTile(int n, int n2, int n3, bool b);
    int executeStaticFunc(int n);
    int queueStaticFunc(int n);
    int getSaveVersion();
    void loadEntityStates(InputStream* IS);
    void saveEntityStates(OutputStream* OS, bool b);
    bool tileObstructsAttack(int n, int n2);
    bool isInputBlockedByScript();
    void updateScriptVars();
    void awardSecret(bool b);
    void addEntityDeathFunc(Entity* entity, int n);
    void removeEntityFunc(Entity* entity);
    void executeEntityFunc(Entity* entity, bool throwAwayLoot);
    void foundLoot(int n, int n2);
    void foundLoot(int n, int n2, int n3, int n4);
    void destroyedObject(int n);
    void raiseCorpses();
    bool isInFront(int n, int n2);
    int VecToDir(int n, int n2, bool b);
    void NormalizeVec(int n, int n2, int* array);
    int64_t FixedSqrt(int64_t n);
    void setMonsterClip(int n, int n2);
    void unsetMonsterClip(int n, int n2);
    bool monsterClipExists(int n, int n2);

    void cleanUpCamMemory();

    const char* GetSaveFile(int i, int i2);
    char* getProfileSaveFileName(const char* name);
    int getMonsterSound(int monsterIdx, int soundType);
};
